#!/bin/bash
# My first script
echo "LOG TIME":`date` > $HOME/assignment.log
echo "HOST NAME: "$HOSTNAME >> $HOME/assignment.log
echo "OS "`lsb_release -d` >> $HOME/assignment.log
echo "Full PATH for HOME: "$HOME >> $HOME/assignment.log
echo "Current Users Logged IN: "`users`	 >> $HOME/assignment.log
echo "Your Groups: "`id -un | groups` >> $HOME/assignment.log
echo "" >> $HOME/assignment.log
echo "----List of All the files in HOME and its SubDirectories----" >> $HOME/assignment.log
echo "" >> $HOME/assignment.log
cd $HOME
ls -pR | grep -v />> $HOME/assignment.log
echo "View assignment.log file"


